#ifndef FREYA_COMPILESYMBOLS_HH
#define FREYA_COMPILESYMBOLS_HH

#include <map>
#include <string>
#include "Singleton.hh"

namespace Utils
{
class CompileSymbols
{
    DEF_SINGLETON(CompileSymbols);

public:

    // Inline definition, because other file is autogenerated.

    const char * get_defs(const char * key)
    {
        if(key != NULL)
        {
            std::string skey(key);
            return compile_defs[skey];
        }
        return NULL;
    }

private:

    std::map<std::string,const char*> compile_defs;
};
}

#endif /* end of include guard: FREYA_COMPILESYMBOLS_HH */

