
#include "CompileSymbols.hh"

/////////////////////////////
// Autogenerated Stuff     //
// generated by:           //
// scripts/amalgamation.rb //
// - do not edit! -        //
/////////////////////////////

namespace Utils
{
CompileSymbols::CompileSymbols() {}
}
